### ISSUE TITLE
Не могу запустить приложение

### ISSUE THREAD

**Issue by FuryOfFools** [myTrackerSDK/mytracker-flutter#1]
Пишет в логах это:

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.my.tracker:mytracker-sdk:3.0.+.
     Required by:
         project :app > project :mytracker_sdk
      > Failed to list versions for com.my.tracker:mytracker-sdk.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/my/tracker/mytracker-sdk/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/my/tracker/mytracker-sdk/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/my/tracker/mytracker-sdk/maven-metadata.xml'.
                  > Read timed out

**Comment by altk** [comment]
Репозиторий jcenter() отключен в прошлом году.
Проверьте ваш build.gradle файл.

**Comment by FuryOfFools** [comment]
Да удалил и все заработало спасибо не знал.
